[package]
name = "rust-template"
version = "0.1.0"
authors = ["vnderlev <vnderlev@protonmail.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "*"
serde = "*"
ureq = { version="*", features=["json"] }
